#!/usr/bin/env ruby

require "socket"
require "zine_brewer"

server = TCPServer.open('localhost', 53623)
loop do
  socket = server.accept
  begin
    filepath = socket.gets.chomp
    zine = ZineBrewer::Application.new(filepath)
    zine.write_out
    socket.write 'Conversion from Markdown to HTML is done. The output files (header.txt / body.txt) are in proof directory.'
  rescue => e
    socket.write e.message
  ensure
    socket.close
  end
end

