#!/usr/bin/env ruby

require "zine_brewer"

begin
  zine = ZineBrewer::Application.new(ARGV[0])
  zine.write_out
  puts 'Conversion from Markdown to HTML is done. The output files (header.txt / body.txt) are in proof directory.'
rescue => e
  puts 'Something wrong...'
  p e
end

